server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Work/native-file-repo
        git:
#          uri: file:///C:\\Users\\User\\Work\\git-local-repo
          uri: https://github.com/rootsong8774/spring-cloud-config.git
#          username: rootsong8774
#          password: "!s64066406"